variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - run_testbench
  - test

bitstream:
  stage: build
  image: vivado2018:2018.3
  tags:
    - vivado
  script:
    - env
    - /opt/Xilinx/Vivado/2018.3/bin/vivado -mode tcl -source cpu/script/build.tcl cpu/thinpad_top.xpr

  artifacts:
    paths:
      - cpu/thinpad_top.runs/impl_1/thinpad_top.bit
      - cpu/thinpad_top.runs/impl_1/runme.log
      - cpu/thinpad_top.runs/synth_1/runme.log

unit-test:
  stage: run_testbench
  image: vivado2018:2018.3
  tags:
    - vivado
  script:
    - export SIMULATION=sim_1
    - /opt/Xilinx/Vivado/2018.3/bin/vivado -mode tcl -source cpu/script/test_cpu.tcl cpu/thinpad_top.xpr

sonar-scanner:
  stage: test
  image: harryleafchen/debian-curl-tar
  tags:
    - secoder
  script:
    - curl -s "http://10.0.0.11/sonar-scanner.tar.gz" -o "/tmp/sonar-scanner.tar.gz"
    - tar -xf "/tmp/sonar-scanner.tar.gz" -C /tmp
    - /tmp/sonar-scanner/bin/sonar-scanner

